Added link to status page at footer
brave/brave-talk pull request #332
Opened 2022-06-09 17:10 UTC by alanzhng

c.f., https://github.com/brave/brave-talk/issues/14

After running into difficulty properly styling the BetterUptime announcement bar as well as security concerns from using a third party script, we decided to defer the status announcement bar and keep the link to the status page in the footer.

2022-06-09 20:01 UTC, mrose17 requested changes
It is probably "good hygiene" to remove the space between ">" and "Service"...

2022-06-09 20:28 UTC, alanzhng commented
Fixed this. Will keep in mind for next time!

2022-06-09 23:18 UTC, mrose17 approved these changes

2022-06-09 23:19 UTC, merged

2022-06-10 15:21 UTC, stephendonner commented
Verified `PASSED` on dev (and staging).

Confirmed link to (Brave's) `Service Status` (`https://status.brave.com/`) appears at the bottom right of the footer, on `https://talk.brave.software/` and `https://talk.bravesoftware.com`:

<img width="1312" alt="Screen Shot 2022-06-10 at 8 19 37 AM" src="https://user-images.githubusercontent.com/387249/173097757-855cc200-684b-49cf-914e-77834c7710ab.png">